# Generated by Django 4.2.19 on 2025-02-27 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_remove_players_headhshot_players_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('total_cost', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('defenders', models.ManyToManyField(related_name='team_defenders', to='players.players')),
                ('forwards', models.ManyToManyField(related_name='team_forwards', to='players.players')),
                ('goalkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_as_goalkeeper', to='players.players')),
                ('midfielders', models.ManyToManyField(related_name='team_midfielders', to='players.players')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
