# Generated by Django 4.2.19 on 2025-02-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
