# Generated by Django 4.2.19 on 2025-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_image_players_upload_to'),
        ('teams', '0004_alter_teams_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='defenders',
            field=models.ManyToManyField(blank=True, related_name='team_defenders', to='players.players'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='forwards',
            field=models.ManyToManyField(blank=True, related_name='team_forwards', to='players.players'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='midfielders',
            field=models.ManyToManyField(blank=True, related_name='team_midfielders', to='players.players'),
        ),
    ]
