# Generated by Django 4.2.19 on 2025-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_team',
            field=models.CharField(default='Arsenal', max_length=50),
            preserve_default=False,
        ),
    ]
