# Generated by Django 4.2.19 on 2025-03-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favourite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
