# Generated by Django 4.2.19 on 2025-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_teams_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=50)),
                ('teams', models.ManyToManyField(related_name='league_teams', to='teams.teams')),
            ],
        ),
    ]
