# Generated by Django 4.2.19 on 2025-02-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_teams_user'),
        ('leagues', '0002_alter_leagues_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='league_teams', to='teams.teams'),
        ),
    ]
