# Generated by Django 4.2.19 on 2025-02-28 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0003_alter_leagues_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
