# Generated by Django 4.2.19 on 2025-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headhshot', models.ImageField(upload_to='headshots/')),
                ('name', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=50)),
                ('price', models.FloatField()),
                ('appearances', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('cleansheets', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('own_goals', models.IntegerField()),
                ('pens_saved', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
