# Generated by Django 4.2.19 on 2025-02-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='headhshot',
        ),
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='players',
            name='appearances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='cleansheets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='own_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='pens_saved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='red_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='yellow_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
