# Generated by Django 4.2.19 on 2025-03-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_players_headhshot_players_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='image',
            new_name='upload_to',
        ),
    ]
