# Generated by Django 4.2.19 on 2025-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_image_players_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='upload_to',
            field=models.ImageField(default='player_images/default.jpg', upload_to='player_images/'),
        ),
    ]
