# Generated by Django 4.2.20 on 2025-03-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_players_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='upload_to',
            field=models.CharField(max_length=500),
        ),
    ]
